apiVersion: v1
kind: Service
metadata:
        name: svc-registry-nginx
spec:
        selector:
                app: registry-app
        ports:
              - name: nginx-tcp80
                protocol: TCP
                port: 80
                targetPort: 80
              - name: nginx-tcp443
                protocol: TCP
                port: 444
                targetPort: 444
                nodePort: 444
        type: NodePort
        
--- 

apiVersion: v1
kind: Service
metadata:
        name: svc-registry-server
spec:
        selector:
                app: registry-app
        ports:
              - name: server-tcp5000
                protocol: TCP
                port: 5000
                nodePort: 5000
        type: NodePort
---

apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: registry-dpt-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-app
        environment: production
    spec:
      containers:
      - name: registry-server-con
        image: registry:2 
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/data"
        ports:
        - name: server-tcp5000
          containerPort: 5000
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: registry-volume-data
        - mountPath: /etc/docker/registry/config.yml
          name: registry-volume-conf
      - name: registry-nginx-con
        image: nginx:1.9
        ports:
        - name: nginx-tcp80
          containerPort: 80
        - name: nginx-tcp443
          containerPort: 444
        imagePullPolicy: Always 
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-volume-data
      #imagePullSecrets:
      #- name: dkhub.funceme.br-registry-secret 
      volumes:
      - name:  registry-volume-data
        hostPath:
          path: /mnt/nas/web/data/registry/dkhub
      - name: registry-volume-conf
        hostPath:
          path: /mnt/nas/web/data/registry/conf/config.yml
      - name:  nginx-volume-data
        hostPath:
          path: /mnt/nas/web/data/registry/conf/nginx